### ISSUE TITLE
Medication and MAR for pharmacy

### ISSUE THREAD

**Issue by bryan-gilbert** [edehr/edehr#1010]
A collection of ideas, each of which could be written as a separate issue

- [ ] Need to see vitamins somewhere along side or merged with the medication list
- [ ] BPMH means Best Possible Medication History
- [ ] Medications that are scheduled (e.g. BiD) we need to allow for scheduled times
- [ ] PRN's can have schedule too e.g BiD, q6h,etc, with scheduled times
- [ ] Need a PRN section on the MAR
- [ ] Typically the med order has a two step process.  One professional creates the medication order and a pharmacist verifies the order.
	- [ ] Need to account for the possibility that the drug is not on formulary it may be the patient's own
- [ ] Meditech  is US based
	- [ ] PharmTech can find patients across the whole health care system (different regions/hospitals)
	- [ ] In the EHR the PharmTech can only change limited info eg allergy
- [ ] Need to augment the allergy page with dropdown options.  These need to include
	- [ ] opioids. ACE inhibitors. antibiotics
- [ ] Need to record allergic reactions to medications

**Comment by bryan-gilbert** [comment]
All of the above now is possible
