### ISSUE TITLE
Server side unit testing coverage

### ISSUE THREAD

**Issue by bryan-gilbert** [edehr/edehr#744]
## Improve server side code unit tests and coverage.  

- [] add a jest config file to tell code coverage to ignore .spec.js files
- [] run coverage and include a snapshot of the current state in a comment in this issue
- [] add tests to important files that have been neglected.
